### ISSUE TITLE
sbt stage and sbt dist fail

### ISSUE THREAD

**Issue by avremel** [yohangz/scala-play-react-seed#11]
The error
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java-play-react-seed@0.0.0 build: `rimraf ../public && react-scripts build && ncp build ../public && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java-play-react-seed@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/avremel/.npm/_logs/2018-12-17T16_29_02_578Z-debug.log
[error] java.lang.Exception: Oops! UI Build crashed.
[error] 	at $5340de8abc0aeaad481e$.$anonfun$$sbtdef$1(/Users/avremel/Desktop/scala_react/ui-build.sbt:56)
[error] 	at $5340de8abc0aeaad481e$.$anonfun$$sbtdef$1$adapted(/Users/avremel/Desktop/scala_react/ui-build.sbt:54)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (uiProdBuild) java.lang.Exception: Oops! UI Build crashed.
```

This is the verbose log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v11.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle java-play-react-seed@0.0.0~prebuild: java-play-react-seed@0.0.0
6 info lifecycle java-play-react-seed@0.0.0~build: java-play-react-seed@0.0.0
7 verbose lifecycle java-play-react-seed@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle java-play-react-seed@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/avremel/Desktop/scala_react/ui/node_modules/.bin:/usr/local/opt/mysql@5.7/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
9 verbose lifecycle java-play-react-seed@0.0.0~build: CWD: /Users/avremel/Desktop/scala_react/ui
10 silly lifecycle java-play-react-seed@0.0.0~build: Args: [ '-c',
10 silly lifecycle   'rimraf ../public && react-scripts build && ncp build ../public && rimraf build' ]
11 silly lifecycle java-play-react-seed@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle java-play-react-seed@0.0.0~build: Failed to exec build script
13 verbose stack Error: java-play-react-seed@0.0.0 build: `rimraf ../public && react-scripts build && ncp build ../public && rimraf build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid java-play-react-seed@0.0.0
15 verbose cwd /Users/avremel/Desktop/scala_react/ui
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/11.4.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v11.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error java-play-react-seed@0.0.0 build: `rimraf ../public && react-scripts build && ncp build ../public && rimraf build`
22 error Exit status 1
23 error Failed at the java-play-react-seed@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by yohangz** [comment]
It works perfectly fine for me. Can you please share the environment details (OS, Node JS version, NPM version)

**Comment by avremel** [comment]
yarn version v1.12.1
nide version v11.4.0
mac High Sierra 10.13.6

I installed all npm packages through yarn.

**Comment by yohangz** [comment]
Can you try installing the node LTS version.

**Comment by avremel** [comment]
yarn build is working fine

![screen shot 2018-12-17 at 12 30 39 pm](https://user-images.githubusercontent.com/10588097/50104302-a4815500-01f7-11e9-981b-7db4063ae745.png)

**Comment by avremel** [comment]
Where is the output of `yarn build` supposed to go?

**Comment by yohangz** [comment]
are you running ```./sbt clean dist``` in project root dir?

**Comment by avremel** [comment]
yes. I would pay for you to debug, if you are interested

**Comment by yohangz** [comment]
:) happy to help, did you try cloning this repo fresh and building it. Just want to make sure this happened prior to making any changes.

**Comment by avremel** [comment]
thanks 👍 
i cloned the repo and did `sbt dist`, worked fine.
let me now copy stuff over...

**Comment by yohangz** [comment]
okay great! i will close this issue then

**Comment by avremel** [comment]
It was failing on a javascript linting error

**Comment by yohangz** [comment]
Linters emit kill signal 1 when errors occur, which is causing the build failure.
